<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Acheteur__CLASSMETADATA__' => 0,
'App__Entity__Categorie__CLASSMETADATA__' => 1,
'App__Entity__Lot__CLASSMETADATA__' => 2,
'App__Entity__Produit__CLASSMETADATA__' => 3,
'App__Entity__Vente__CLASSMETADATA__' => 4,
'App__Entity__CommissairePriseur__CLASSMETADATA__' => 5,
'App__Entity__Personne__CLASSMETADATA__' => 6,
'App__Entity__Photo__CLASSMETADATA__' => 7,
'App__Entity__Vendeur__CLASSMETADATA__' => 8,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Acheteur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Acheteur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AcheteurRepository',
                ],
                'identifier' => [
                    [
                        'idacheteur',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idacheteur' => [
                            'fieldName' => 'idacheteur',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'idacheteur',
                        ],
                        'nomacheteur' => [
                            'fieldName' => 'nomacheteur',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'nomacheteur',
                        ],
                        'prenomacheteur' => [
                            'fieldName' => 'prenomacheteur',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'prenomacheteur',
                        ],
                        'adressemail' => [
                            'fieldName' => 'adressemail',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'adressemail',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'password',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idacheteur' => 'idacheteur',
                        'nomacheteur' => 'nomacheteur',
                        'prenomacheteur' => 'prenomacheteur',
                        'adressemail' => 'adressemail',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'idacheteur' => 'idacheteur',
                        'nomacheteur' => 'nomacheteur',
                        'prenomacheteur' => 'prenomacheteur',
                        'adressemail' => 'adressemail',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'acheteur',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Categorie',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Categorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategorieRepository',
                ],
                'identifier' => [
                    [
                        'idcategorie',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idcategorie' => [
                            'fieldName' => 'idcategorie',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'idcategorie',
                        ],
                        'nomcategorie' => [
                            'fieldName' => 'nomcategorie',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'nomcategorie',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idcategorie' => 'idcategorie',
                        'nomcategorie' => 'nomcategorie',
                    ],
                ],
                'columnNames' => [
                    [
                        'idcategorie' => 'idcategorie',
                        'nomcategorie' => 'nomcategorie',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'categorie',
                    ],
                ],
                'associationMappings' => [
                    [
                        'idproduit' => [
                            'fieldName' => 'idproduit',
                            'mappedBy' => 'categorie_idcategorie',
                            'targetEntity' => 'App\\Entity\\Produit',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Categorie',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Lot',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Lot',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\LotRepository',
                ],
                'identifier' => [
                    [
                        'idlot',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idlot' => [
                            'fieldName' => 'idlot',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'idlot',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idlot' => 'idlot',
                    ],
                ],
                'columnNames' => [
                    [
                        'idlot' => 'idlot',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'lot',
                    ],
                ],
                'associationMappings' => [
                    [
                        'idproduit' => [
                            'fieldName' => 'idproduit',
                            'mappedBy' => 'lot_idlot',
                            'targetEntity' => 'App\\Entity\\Produit',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\Lot',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Produit',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Produit',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProduitRepository',
                ],
                'identifier' => [
                    [
                        'idproduit',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idproduit' => [
                            'fieldName' => 'idproduit',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'idproduit',
                        ],
                        'prix' => [
                            'fieldName' => 'prix',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'prix',
                        ],
                        'nomproduit' => [
                            'fieldName' => 'nomproduit',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'nomproduit',
                        ],
                        'categorie' => [
                            'fieldName' => 'categorie',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'categorie',
                        ],
                        'numproduit' => [
                            'fieldName' => 'numproduit',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'numproduit',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idproduit' => 'idproduit',
                        'prix' => 'prix',
                        'nomproduit' => 'nomproduit',
                        'categorie' => 'categorie',
                        'numproduit' => 'numproduit',
                    ],
                ],
                'columnNames' => [
                    [
                        'idproduit' => 'idproduit',
                        'prix' => 'prix',
                        'nomproduit' => 'nomproduit',
                        'categorie' => 'categorie',
                        'numproduit' => 'numproduit',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'produit',
                    ],
                ],
                'associationMappings' => [
                    [
                        'lot_idlot' => [
                            'fieldName' => 'lot_idlot',
                            'joinColumns' => [
                                [
                                    'name' => 'lot_idlot',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'idlot',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'idproduit',
                            'targetEntity' => 'App\\Entity\\Lot',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Produit',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'lot_idlot' => 'idlot',
                            ],
                            'joinColumnFieldNames' => [
                                'lot_idlot' => 'lot_idlot',
                            ],
                            'targetToSourceKeyColumns' => [
                                'idlot' => 'lot_idlot',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'categorie_idcategorie' => [
                            'fieldName' => 'categorie_idcategorie',
                            'joinColumns' => [
                                [
                                    'name' => 'categorie_idcategorie',
                                    'unique' => false,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'idcategorie',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'idproduit',
                            'targetEntity' => 'App\\Entity\\Categorie',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Produit',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'categorie_idcategorie' => 'idcategorie',
                            ],
                            'joinColumnFieldNames' => [
                                'categorie_idcategorie' => 'categorie_idcategorie',
                            ],
                            'targetToSourceKeyColumns' => [
                                'idcategorie' => 'categorie_idcategorie',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Vente',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Vente',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\VenteRepository',
                ],
                'identifier' => [
                    [
                        'idvente',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'idvente' => [
                            'fieldName' => 'idvente',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'idvente',
                        ],
                        'lieu' => [
                            'fieldName' => 'lieu',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'lieu',
                        ],
                        'date' => [
                            'fieldName' => 'date',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'date',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'idvente' => 'idvente',
                        'lieu' => 'lieu',
                        'date' => 'date',
                    ],
                ],
                'columnNames' => [
                    [
                        'idvente' => 'idvente',
                        'lieu' => 'lieu',
                        'date' => 'date',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'vente',
                    ],
                ],
                'associationMappings' => [
                    [
                        'idlot' => [
                            'fieldName' => 'idlot',
                            'targetEntity' => 'App\\Entity\\Lot',
                            'joinColumns' => [
                                [
                                    'name' => 'idlot',
                                    'unique' => true,
                                    'nullable' => true,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'idlot',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Vente',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'idlot' => 'idlot',
                            ],
                            'joinColumnFieldNames' => [
                                'idlot' => 'idlot',
                            ],
                            'targetToSourceKeyColumns' => [
                                'idlot' => 'idlot',
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\CommissairePriseur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\CommissairePriseur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CommissairePriseurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Prénom' => [
                            'fieldName' => 'Prénom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'prénom',
                        ],
                        'Nom' => [
                            'fieldName' => 'Nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'Région' => [
                            'fieldName' => 'Région',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'région',
                        ],
                        'Département' => [
                            'fieldName' => 'Département',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'département',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'prénom' => 'Prénom',
                        'nom' => 'Nom',
                        'région' => 'Région',
                        'département' => 'Département',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Prénom' => 'prénom',
                        'Nom' => 'nom',
                        'Région' => 'région',
                        'Département' => 'département',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'commissaire_priseur',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Personne',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Personne',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PersonneRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'personne',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Photo',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Photo',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PhotoRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'url' => [
                            'fieldName' => 'url',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'url',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'url' => 'url',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'url' => 'url',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'photo',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Vendeur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Vendeur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\VendeurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Nom' => [
                            'fieldName' => 'Nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                        'Prénom' => [
                            'fieldName' => 'Prénom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 45,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'prénom',
                        ],
                        'IdProduit' => [
                            'fieldName' => 'IdProduit',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'id_produit',
                        ],
                        'Ordre_Achat' => [
                            'fieldName' => 'Ordre_Achat',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => null,
                            'precision' => null,
                            'columnName' => 'ordre_achat',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nom' => 'Nom',
                        'prénom' => 'Prénom',
                        'id_produit' => 'IdProduit',
                        'ordre_achat' => 'Ordre_Achat',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nom' => 'nom',
                        'Prénom' => 'prénom',
                        'IdProduit' => 'id_produit',
                        'Ordre_Achat' => 'ordre_achat',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'vendeur',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
