<?php

namespace ContainerTNcG41W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcheteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xMQ4koJ.App\Entity\Acheteur' shared service.
     *
     * @return \App\Entity\Acheteur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xMQ4koJ": it references class "App\\Entity\\Acheteur" but no such service exists.');
    }
}
