<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6TvIixp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6TvIixp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6TvIixp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6TvIixp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6TvIixp\App_KernelDevDebugContainer([
    'container.build_hash' => '6TvIixp',
    'container.build_id' => '9eb8bb33',
    'container.build_time' => 1621763125,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6TvIixp');
