<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2OmZuFg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2OmZuFg/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container2OmZuFg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container2OmZuFg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container2OmZuFg\App_KernelProdContainer([
    'container.build_hash' => '2OmZuFg',
    'container.build_id' => '6e153322',
    'container.build_time' => 1621978376,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2OmZuFg');
