<?php

namespace Container2OmZuFg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ABpdEnService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6ABpdEn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ABpdEn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LotRepository' => ['privates', 'App\\Repository\\LotRepository', 'getLotRepositoryService', true],
        ], [
            'LotRepository' => 'App\\Repository\\LotRepository',
        ]);
    }
}
