<?php

namespace Container2OmZuFg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1GjiQzsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1GjiQzs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1GjiQzs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vente' => ['privates', '.errored..service_locator.1GjiQzs.App\\Entity\\Vente', NULL, 'Cannot autowire service ".service_locator.1GjiQzs": it references class "App\\Entity\\Vente" but no such service exists.'],
        ], [
            'vente' => 'App\\Entity\\Vente',
        ]);
    }
}
