<?php

namespace Container2OmZuFg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLotService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.TmEBFl2.App\Entity\Lot' shared service.
     *
     * @return \App\Entity\Lot
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TmEBFl2": it references class "App\\Entity\\Lot" but no such service exists.');
    }
}
