<?php

namespace Container4G9oIug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAcheteurTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AcheteurType' shared autowired service.
     *
     * @return \App\Form\AcheteurType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AcheteurType'] = new \App\Form\AcheteurType();
    }
}
