<?php

namespace Container5NEYtIi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KDXZUyGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KDXZUyG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KDXZUyG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'venteRepository' => ['privates', 'App\\Repository\\VenteRepository', 'getVenteRepositoryService', true],
        ], [
            'venteRepository' => 'App\\Repository\\VenteRepository',
        ]);
    }
}
