<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Acheteur extends \App\Entity\Acheteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'idacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'nomacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'prenomacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'adressemail', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'password'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'idacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'nomacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'prenomacheteur', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'adressemail', '' . "\0" . 'App\\Entity\\Acheteur' . "\0" . 'password'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Acheteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getidacheteur(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getidacheteur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidacheteur', []);

        return parent::getidacheteur();
    }

    /**
     * {@inheritDoc}
     */
    public function getnomacheteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getnomacheteur', []);

        return parent::getnomacheteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setnomacheteur(string $nomacheteur): \App\Entity\Acheteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setnomacheteur', [$nomacheteur]);

        return parent::setnomacheteur($nomacheteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getprenomacheteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getprenomacheteur', []);

        return parent::getprenomacheteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setprenomacheteur(string $prenomacheteur): \App\Entity\Acheteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setprenomacheteur', [$prenomacheteur]);

        return parent::setprenomacheteur($prenomacheteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressemail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressemail', []);

        return parent::getAdressemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressemail(string $adressemail): \App\Entity\Acheteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressemail', [$adressemail]);

        return parent::setAdressemail($adressemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Acheteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

}
