<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'idproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nomproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'numproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'lot_idlot', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categorie_idcategorie'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'idproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nomproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'numproduit', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'lot_idlot', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'categorie_idcategorie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getidproduit(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getidproduit();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidproduit', []);

        return parent::getidproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function getnomproduit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getnomproduit', []);

        return parent::getnomproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setnomproduit(string $nomproduit): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setnomproduit', [$nomproduit]);

        return parent::setnomproduit($nomproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getcategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcategorie', []);

        return parent::getcategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setcategorie(string $categorie): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcategorie', [$categorie]);

        return parent::setcategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getnumproduit(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getnumproduit', []);

        return parent::getnumproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setnumproduit(int $numproduit): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setnumproduit', [$numproduit]);

        return parent::setnumproduit($numproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getprix(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getprix', []);

        return parent::getprix();
    }

    /**
     * {@inheritDoc}
     */
    public function setprix(int $prix): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setprix', [$prix]);

        return parent::setprix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getlot_idlot(): ?\App\Entity\Lot
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getlot_idlot', []);

        return parent::getlot_idlot();
    }

    /**
     * {@inheritDoc}
     */
    public function setlot_idlot(?\App\Entity\Lot $lot_idlot): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setlot_idlot', [$lot_idlot]);

        return parent::setlot_idlot($lot_idlot);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieIdcategorie(): ?\App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieIdcategorie', []);

        return parent::getCategorieIdcategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieIdcategorie(?\App\Entity\Categorie $categorie_idcategorie): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieIdcategorie', [$categorie_idcategorie]);

        return parent::setCategorieIdcategorie($categorie_idcategorie);
    }

}
